services:
  # backend:
  #   build:
  #     context: .
  #     no_cache: true
  #   container_name: my_subscription_backend
  #   env_file:
  #     - .env.prod
  #   ports:
  #     - "8083:8083"
  #   depends_on:
  #     - postgres
  #     - redis
  #   restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: my_persona_postgress
    environment:
      POSTGRES_DB: ai_persona
      POSTGRES_USER: aj_user
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine3.22
    container_name: my_persona_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: